version: '3.2'

services:

  jupyter:
    build:
      context: ./jupyter
      # args:
      #   - http_proxy=http://webproxy.example.com
      #   - https_proxy=http://webproxy.example.com
    image: jupyter_docker
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.password=sha256:622826ca63aa:0d26deb40a5477b7835b9fdfacc411913564e23e13e4eb5105dd00128fd2449f
    volumes:
      - ./jupyter/notebooks:/code
    ports:
      - 8888:8888
    networks:
      - lab_network

  app:
    build:
      context: ./fastapi
      # args:
      #   - http_proxy=http://webproxy.example.com
      #   - https_proxy=http://webproxy.example.com
    image: fastapi_docker
    command: uvicorn fastapi-main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./fastapi/code:/code
    restart: always
    ports:
      - 8000:8000
    networks:
      - lab_network

  couchdb:
    image: couchdb
    restart: always
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=mysecretpassword
    ports:
      - 5984:5984
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - lab_network

volumes:
  couchdb_data:
    driver: local


networks:
  lab_network:
    external: false